spring:
  datasource:
    url: jdbc:mysql://192.168.61.126:3306/yxp_user?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&autoReconnect=true&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: '{cipher}1d20166b63febeafdfba9dbeddd712d4403b6d390c94a271b1c4d8783684ac87'
    password: '{cipher}ac7fa9f6cc1eab7d78f62c32ca6698fb3d7b0f6db75388cd8a1260c5539484cc'